/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthWorkoutRouteImport } from './routes/_auth/workout'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthProgramsRouteImport } from './routes/_auth/programs'
import { Route as AuthNutritionRouteImport } from './routes/_auth/nutrition'
import { Route as AuthProgramsIndexRouteImport } from './routes/_auth/programs/index'
import { Route as AuthNutritionIndexRouteImport } from './routes/_auth/nutrition/index'
import { Route as AuthProgramsProgramIdRouteImport } from './routes/_auth/programs/$programId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthWorkoutRoute = AuthWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProgramsRoute = AuthProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthNutritionRoute = AuthNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProgramsIndexRoute = AuthProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthProgramsRoute,
} as any)
const AuthNutritionIndexRoute = AuthNutritionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthNutritionRoute,
} as any)
const AuthProgramsProgramIdRoute = AuthProgramsProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => AuthProgramsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof AuthNutritionRouteWithChildren
  '/programs': typeof AuthProgramsRouteWithChildren
  '/settings': typeof AuthSettingsRoute
  '/workout': typeof AuthWorkoutRoute
  '/programs/$programId': typeof AuthProgramsProgramIdRoute
  '/nutrition/': typeof AuthNutritionIndexRoute
  '/programs/': typeof AuthProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof AuthSettingsRoute
  '/workout': typeof AuthWorkoutRoute
  '/': typeof AuthIndexRoute
  '/programs/$programId': typeof AuthProgramsProgramIdRoute
  '/nutrition': typeof AuthNutritionIndexRoute
  '/programs': typeof AuthProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/nutrition': typeof AuthNutritionRouteWithChildren
  '/_auth/programs': typeof AuthProgramsRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/workout': typeof AuthWorkoutRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/programs/$programId': typeof AuthProgramsProgramIdRoute
  '/_auth/nutrition/': typeof AuthNutritionIndexRoute
  '/_auth/programs/': typeof AuthProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/nutrition'
    | '/programs'
    | '/settings'
    | '/workout'
    | '/programs/$programId'
    | '/nutrition/'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/workout'
    | '/'
    | '/programs/$programId'
    | '/nutrition'
    | '/programs'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/nutrition'
    | '/_auth/programs'
    | '/_auth/settings'
    | '/_auth/workout'
    | '/_auth/'
    | '/_auth/programs/$programId'
    | '/_auth/nutrition/'
    | '/_auth/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/workout': {
      id: '/_auth/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AuthWorkoutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/programs': {
      id: '/_auth/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AuthProgramsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/nutrition': {
      id: '/_auth/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthNutritionRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/programs/': {
      id: '/_auth/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof AuthProgramsIndexRouteImport
      parentRoute: typeof AuthProgramsRoute
    }
    '/_auth/nutrition/': {
      id: '/_auth/nutrition/'
      path: '/'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof AuthNutritionIndexRouteImport
      parentRoute: typeof AuthNutritionRoute
    }
    '/_auth/programs/$programId': {
      id: '/_auth/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof AuthProgramsProgramIdRouteImport
      parentRoute: typeof AuthProgramsRoute
    }
  }
}

interface AuthNutritionRouteChildren {
  AuthNutritionIndexRoute: typeof AuthNutritionIndexRoute
}

const AuthNutritionRouteChildren: AuthNutritionRouteChildren = {
  AuthNutritionIndexRoute: AuthNutritionIndexRoute,
}

const AuthNutritionRouteWithChildren = AuthNutritionRoute._addFileChildren(
  AuthNutritionRouteChildren,
)

interface AuthProgramsRouteChildren {
  AuthProgramsProgramIdRoute: typeof AuthProgramsProgramIdRoute
  AuthProgramsIndexRoute: typeof AuthProgramsIndexRoute
}

const AuthProgramsRouteChildren: AuthProgramsRouteChildren = {
  AuthProgramsProgramIdRoute: AuthProgramsProgramIdRoute,
  AuthProgramsIndexRoute: AuthProgramsIndexRoute,
}

const AuthProgramsRouteWithChildren = AuthProgramsRoute._addFileChildren(
  AuthProgramsRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthNutritionRoute: typeof AuthNutritionRouteWithChildren
  AuthProgramsRoute: typeof AuthProgramsRouteWithChildren
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthWorkoutRoute: typeof AuthWorkoutRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthNutritionRoute: AuthNutritionRouteWithChildren,
  AuthProgramsRoute: AuthProgramsRouteWithChildren,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthWorkoutRoute: AuthWorkoutRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
